### PR TITLE
Fix for budget annual budget output

### LINKED ISSUE #188: budgets are not written at the end of month 12 or at the end of year for a 1 year run
For a one year run, if the budget diagnostics are on and the annual and monthly budgets are requested, then no monthly budgets appear for December and no annual budgets appear.

### PR DESCRIPTION
**Pull request by mvertens**
### Description of changes
Fixes #188 where budgets are not written out for December or annually for a 1 year run

### Specific notes
The fix is to use nexttime rather than currtime to trigger budget output. This is consistent with the time stamp of history and restart files as well in cmeps.

Contributors other than yourself, if any: None

Fixes: #188 

Are changes expected to change answers?
 - [x] bit for bit
 - [ ] different at roundoff level
 - [ ] more substantial

Any User Interface Changes (namelist or namelist defaults changes)?
 - [ ] Yes
 - [x] No

Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required):
This only effects CESM configurations. 
- Verified that an A compset at f19_g17 run for a year with budgets turned on produced both annual budget information as well as a budget entry for month 12.
- Verified that for a 3 month run, B1850 at f19_g17, budgets were created for month 3 and that the results were bfb with a run without these cmeps changes.

Hashes used for testing:
- [x] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - tag: cesm2_3_beta02

### CODE REVIEW

File: mediator/med_diag_mod.F90 [hunk 1]
```diff
@@ -421,95 +426,96 @@ end function get_diag_attribute
    end subroutine med_diag_init
 
   !===============================================================================
-  subroutine med_diag_zero( gcomp, mode, rc)
+  subroutine med_diag_zero_mode(mode, rc )
```
Comment (jedwards4b) [inline mediator/med_diag_mod.F90:429]: remove the space after rc

**Review by jedwards4b — APPROVED** [review]

File: mediator/med_diag_mod.F90 (hunk 1 above)
Comment (mvertens) [reply mediator/med_diag_mod.F90:429]: Done

**Review by DeniseWorthen — APPROVED** [review]
Should have no impact on ufs
