### PR TITLE
fix issue with scaling over instances

### LINKED ISSUE #326: Multi-instances init time scaling linearly.
I did some timings with different numbers of instances:  SMS, SMS_C2, and SMS_C5
It looks like the init time is scaling linearly to the number of instances.
```
SMS_P108x1_Lh1_Vnuopc.f09_f09_mg17.FHIST_DARTC6      Init Time   :     228.722 seconds
SMS_C2_P108x1_Lh1_Vnuopc.f09_f09_mg17.FHIST_DARTC6   Init Time   :     457.833 seconds
SMS_C5_P108x1_Lh1_Vnuopc.f09_f09_mg17.FHIST_DARTC6   Init Time   :    1153.911 seconds
```
This is an issue because a C80 test would take 5 hours to initialize.

I also did a couple of QPC6 tests
```
SMS_P108x1_Lh1_Vnuopc.f09_f09_mg17.QPC6      Init Time   :      11.278 seconds
SMS_C5_P108x1_Lh1_Vnuopc.f09_f09_mg17.QPC6   Init Time   :      53.642 seconds 
```

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Remove a performance funnel in ensemble_driver which caused linear scaling with number of members

### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #): Fixes #326

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

File: cesm/driver/ensemble_driver.F90 [hunk 1]
```diff
@@ -203,69 +203,68 @@ subroutine SetModelServices(ensemble_driver, rc)
     !-------------------------------------------
 
     allocate(petList(ntasks_per_member))
+    ! which driver instance is this?
+    inst = localPet/ntasks_per_member + 1
```
Comment (mvertens) [inline cesm/driver/ensemble_driver.F90:207]: @jedwards4b - very clever! Have you checked if this solved the performance problem?

**Comment by fischer-ncar** [comment]
I'm cleaning out my office this morning.  So I'll give it a try this afternoon.

**Comment by fischer-ncar** [comment]
This is what I'm seeing for C2 and C5.  So I can confirm a considerable improvement.

```
Region                                                                       PETs   PEs    Count    Mean (s)    Min (s)     Min PET Max (s)     Max PET
[ensemble] Init 1                                                            216    216    1        226.9003    226.8974    109     226.9062    18   
[ensemble] Init 1                                                            540    540    1        222.5143    222.5101    113     222.5175    216
```

**Review by fischer-ncar — APPROVED** [review]
